backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Live Updates
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  
  - name: slider
    label: "Slider"
    files:
      - label: "Slides"
        name: "slides"
        extenstion: markdown
        file: "site/content/slider/slides.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { name: caption1, label: 1-Caption, widget: string }
          - { name: title1, label: 1-Title, widget: text }
          - { name: caption2, label: 2-Caption, widget: string }
          - { name: title2, label: 2-Title, widget: text }
          - { name: caption3, label: 3-Caption, widget: string }
          - { name: title3, label: 3-Title, widget: text }
          - { name: caption4, label: 4-Caption, widget: string }
          - { name: title4, label: 4-Title, widget: text }

  - name: legacy
    label: "Legacy Section"
    files:
      - label: "Block 1"
        name: "block_1"
        extenstion: markdown
        file: "site/content/legacy/legacy_1.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Block 2"
        name: "block_2"
        file: "site/content/legacy/legacy_2.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Block 3"
        name: "block_3"
        file: "site/content/legacy/legacy_3.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }
      
      - label: "Block 4"
        name: "block_4"
        file: "site/content/legacy/legacy_4.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

  - name: investing
    label: "Investing Section"
    files:
      - label: "Block 1"
        name: "block_1"
        extenstion: markdown
        file: "site/content/investing/investing_1.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }
      
      - label: "Block 2"
        name: "block_2"
        extenstion: markdown
        file: "site/content/investing/investing_2.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Block 3"
        name: "block_3"
        extenstion: markdown
        file: "site/content/investing/investing_3.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }
      
      - label: "Block 4"
        name: "block_4"
        extenstion: markdown
        file: "site/content/investing/investing_4.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }
      
      - label: "Disclaimer"
        name: "disclaimer"
        file: "site/content/investing/disclaimer.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { name: disclaimer, label: Disclaimer, widget: text }

  - name: performance
    label: "Performance Section"
    files: 
      - label: "Fund Names"
        name: "fund_names"
        file: "site/content/performance/performance.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { name: fund_1, label: Fund 1, widget: string }
          - { name: fund_2, label: Fund 2, widget: string }
          - { name: fund_3, label: Fund 3, widget: string }

  - name: perfomance_tables
    label: "Performance Tables"
    folder: "site/content/performance"
    create: true
    slug: "{{fund_name}}"
    fields:
      - { name: fund_name, label: Fund Name, widget: string }
      - label: Years
        label_singular: "Fund Year"
        name: "year"
        widget: list
        fields:
          - {label: Year, name: year, widget: number}
          - label: "months"
            name: months
            widget: object
            fields:
              - {name: percentage-01, label: Jan %, widget: number, default: 0}
              - {name: percentage-02, label: Feb %, widget: number, default: 0}
              - {name: percentage-03, label: Mar %, widget: number, default: 0}
              - {name: percentage-04, label: Apr %, widget: number, default: 0}
              - {name: percentage-05, label: May %, widget: number, default: 0}
              - {name: percentage-06, label: Jun %, widget: number, default: 0}
              - {name: percentage-07, label: Jul %, widget: number, default: 0}
              - {name: percentage-08, label: Aug %, widget: number, default: 0}
              - {name: percentage-09, label: Sep %, widget: number, default: 0}
              - {name: percentage-10, label: Oct %, widget: number, default: 0}
              - {name: percentage-11, label: Nov %, widget: number, default: 0}
              - {name: percentage-12, label: Dec %, widget: number, default: 0}

  - name: contact
    label: "Contact Section"
    files:
      - label: "Contact Details"
        name: "contact_details"
        file: "site/content/contact/contact_details.md"
        fields:
          - { name: data, label: Data, widget: date }
          - { name: address, label: Address, widget: text }
          - { name: number, label: Contact Number, widget: string }
          - { name: email, label: Email Address, widget: string }

      - label: "Block 1"
        name: "block_1"
        extenstion: markdown
        file: "site/content/contact/contact_1.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Social Media Block"
        name: "social_media"
        file: "site/content/contact/contact_2.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { name: social, label: Social Accounts, widget: list, fields: [{name: name, label: Social Acc. Name, widget: string}, {name: image, label: Image, widget: image}, {name: text, label: Link Text, widget: text}, {name: url, label: URL, widget: text}]}
