backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Live Updates
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: sections
    label: "Sections"
    files:
      - label: "Contact Section"
        name: "contact"
        file: "site/content/about.md"
        fields:
          - {label: Section Title, name: title, widget: string }
          - {label: Block 1, name: block_1, widget: markdown }
          - {label: Block 2, name: block_2, widget: markdown }
          - {label: Block 3, name: block_3, widget: markdown }