backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Live Updates
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: contact
    label: "Contact Us"
    files:
      - label: "1st Block"
        name: "block_1"
        extenstion: markdown
        file: "site/content/contact_1.md"
        fields:
          - {label: Body, name: body, widget: markdown }

      - label: "2nd Block"
        name: "block_2"
        file: "site/content/contact_2.md"
        fields:
          - {label: Body, name: body, widget: markdown }

      - label: "3rd Block"
        name: "block_3"
        file: "site/content/contact_3.md"
        fields:
          - {label: Body, name: body, widget: markdown }