backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Live Updates
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title, widget: string }
      - { name: thumbnail, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: investing
    label: "Investing Section"
    files:
      - label: "Block 1"
        name: "block_1"
        extenstion: markdown
        file: "site/content/investing/investing_1.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }
      
      - label: "Block 2"
        name: "block_2"
        extenstion: markdown
        file: "site/content/investing/investing_2.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Block 3"
        name: "block_3"
        extenstion: markdown
        file: "site/content/investing/investing_3.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }
      
      - label: "Block 4"
        name: "block_4"
        extenstion: markdown
        file: "site/content/investing/investing_4.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

  - name: contact
    label: "Contact Section"
    files:
      - label: "Block 1"
        name: "block_1"
        extenstion: markdown
        file: "site/content/contact/contact_1.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Block 2"
        name: "block_2"
        file: "site/content/contact/contact_2.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }

      - label: "Block 3"
        name: "block_3"
        file: "site/content/contact/contact_3.md"
        fields:
          - { name: date, label: Date, widget: date }
          - { label: Body, name: body, widget: markdown }